"Name: \TY:CL_HRPA_VIEKN\ME:VIEKN\SE:BEGIN\EI
ENHANCEMENT 0 Z_HR_USEREXIT_SKIP_INF0003.
*
check sy-cprog <> 'ZHR_WORKDAY_TO_SAP_EMPMASTER'
AND   sy-cprog <>  'YTEST_WORKDAY_TO_SAP_EMPMASTER'.
ENDENHANCEMENT.
