*&---------------------------------------------------------------------*
*& Include          ZFI_EBUILDER_S4_ACCNT_TOP
*&---------------------------------------------------------------------*

TYPES : BEGIN OF ty_file,
          ediuser(10)     TYPE c,
          edibatch(15)    TYPE c,
          tranno(10)      TYPE c,
          lineno(10)      TYPE c,
          sccess_prc      TYPE c,
          costctr(10)     TYPE c,
          job_no(18)      TYPE c,
          co_num(10)      TYPE c,
          commit_no(25)   TYPE c,
          inv_no(16)      TYPE c,
          inv_dat(10)     TYPE c,
          inv_itm_des(50) TYPE c,
          net_payinv(25)  TYPE c,
          cost_code(10)   TYPE c,
          subledg(10)     TYPE c,
          subtype         TYPE c,
          net_payline(25) TYPE c,
          pr_cntr(10)     TYPE c,
          usr_id(10)      TYPE c,
          pgm_id(10)      TYPE c,
          wk_id(10)       TYPE c,
          date_xprt(10)   TYPE c,
          compno(10)      TYPE c,
          commit_item(10) TYPE c,
        END OF ty_file.

TYPES : BEGIN OF ty_filefull,
          ediuser(10)     TYPE c,
          edibatch(15)    TYPE c,
          tranno(10)      TYPE c,
          lineno(10)      TYPE c,
          sccess_prc      TYPE c,
          costctr(10)     TYPE c,
          job_no(18)      TYPE c,
          co_num(10)      TYPE c,
          commit_no(25)   TYPE c,
          inv_no(100)     TYPE c,
          inv_dat(10)     TYPE c,
          inv_itm_des(50) TYPE c,
          net_payinv(25)  TYPE c,
          cost_code(10)   TYPE c,
          subledg(10)     TYPE c,
          subtype         TYPE c,
          net_payline(25) TYPE c,
          pr_cntr(10)     TYPE c,
          usr_id(10)      TYPE c,
          pgm_id(10)      TYPE c,
          wk_id(10)       TYPE c,
          date_xprt(10)   TYPE c,
          compno(10)      TYPE c,
          commit_item(10) TYPE c,
        END OF ty_filefull.

DATA : gt_file   TYPE TABLE OF ty_file,
       gs_file   TYPE ty_file,
       gt_data   TYPE TABLE OF zfis_ebuildr_s4_accpay,
       gs_data   TYPE zfis_ebuildr_s4_accpay,
       gt_lookup TYPE TABLE OF zfi_ebld_gl_tab,
       gt_ret2   TYPE TABLE OF bapiret2.

DATA : gt_filefull TYPE TABLE OF ty_filefull,
       gs_filefull TYPE ty_filefull.
