*&---------------------------------------------------------------------*
*& Include          ZFIAP_CONCUR_PAYMENT_CONF_SEL
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-t01.
  PARAMETERS: cb_int34 AS CHECKBOX,
              cb_it111 AS CHECKBOX.
  SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-t02.
    PARAMETERS: cb_prxy AS CHECKBOX,
                cb_alv  AS CHECKBOX,
                cb_mail AS CHECKBOX.
    SELECT-OPTIONS: s_edate FOR gv_edate OBLIGATORY.
    PARAMETERS: p_email TYPE ad_smtpadr.
    PARAMETERS: p_path LIKE rlgrap-filename.
    SELECTION-SCREEN BEGIN OF BLOCK b3  WITH FRAME TITLE TEXT-t03.

      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_hnz AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-001.
        PARAMETERS: p_hnz_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-002.
        PARAMETERS: p_hnz_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_hnz_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_hpa AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-003.
        PARAMETERS: p_hpa_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-004.
        PARAMETERS: p_hpa_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_hpa_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_hpl AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-005.
        PARAMETERS: p_hpl_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-006.
        PARAMETERS: p_hpl_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_hpl_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_hpw AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-007.
        PARAMETERS: p_hpw_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-008.
        PARAMETERS: p_hpw_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_hpw_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_lfv AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-009.
        PARAMETERS: p_lfv_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-010.
        PARAMETERS: p_lfv_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_lfv_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_v97 AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-011.
        PARAMETERS: p_v97_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-012.
        PARAMETERS: p_v97_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_v97_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
      SELECTION-SCREEN BEGIN OF LINE.
        PARAMETERS: p_v98 AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-013.
        PARAMETERS: p_v98_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-014.
        PARAMETERS: p_v98_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_v98_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
      SELECTION-SCREEN END OF LINE.
 SELECTION-SCREEN BEGIN OF LINE.         "+p
        PARAMETERS: p_hpn AS CHECKBOX.
        SELECTION-SCREEN COMMENT (7) TEXT-015.
        PARAMETERS: p_hpn_dt TYPE sy-datum.
        SELECTION-SCREEN COMMENT (16) TEXT-016.
        PARAMETERS: p_hpn_ps TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-017.
        PARAMETERS: p_hpn_pe TYPE sy-datum.
        SELECTION-SCREEN COMMENT (21) TEXT-018.
         SELECTION-SCREEN END OF LINE.        "+p
    SELECTION-SCREEN END OF BLOCK b3.

  SELECTION-SCREEN END OF BLOCK b2.

SELECTION-SCREEN END OF BLOCK b1.
