"Name: \PR:RBDSEMAT\EX:RBDSEMAT_04\EI
ENHANCEMENT 0 ZMM_ENH_MATMAS_SEL_SCREEN.
*DATA: lv_mat12 TYPE char20 VALUE 'MaType'.
*lv_mat12 = 'MaType'.
*SELECTION-SCREEN BEGIN OF LINE.
*  SELECTION-SCREEN COMMENT 5(10) lv_mat12.
   SELECT-OPTIONS: s_mtart FOR mara-mtart NO INTERVALS.
*  SELECTION-SCREEN COMMENT (20) tvar.
*SELECTION-SCREEN END OF LINE.

ENDENHANCEMENT.
